export enum SyncOperation {
  // Dataset operations
  CREATE_DATASET = "CREATE_DATASET",
  UPDATE_DATASET = "UPDATE_DATASET",
  DELETE_DATASET = "DELETE_DATASET",

  // Measurement operations
  ADD_MEASUREMENT = "ADD_MEASUREMENT",
  UPDATE_MEASUREMENT = "UPDATE_MEASUREMENT",
  REMOVE_MEASUREMENT = "REMOVE_MEASUREMENT",

  // View operations
  ADD_VIEW = "ADD_VIEW",
  REMOVE_VIEW = "REMOVE_VIEW",
}
