// Generated by ts-to-zod
import { z } from "zod";

export const unitSchema = z.union([
  z.literal("seconds"),
  z.literal("minutes"),
  z.literal("hours"),
  z.literal("days"),
  z.literal("weeks"),
  z.literal("months"),
  z.literal("years"),
  z.literal("meters"),
  z.literal("kilometers"),
  z.literal("miles"),
  z.literal("grams"),
  z.literal("kilograms"),
  z.literal("pounds"),
  z.literal("celsius"),
  z.literal("fahrenheit"),
  z.literal("percentage"),
  z.literal("bytes"),
  z.literal("kilobytes"),
  z.literal("megabytes"),
  z.literal("gigabytes"),
  z.literal("terabytes"),
  z.literal("dollars"),
  z.literal("euros"),
  z.literal("rupees"),
  z.literal("count"),
]);

export const viewTypeSchema = z.union([
  z.literal("line"),
  z.literal("bar"),
  z.literal("area"),
  z.literal("pie"),
  z.literal("scatter"),
]);

export const measurementSchema = z.object({
  id: z.optional(z.string()),
  timestamp: z.string(),
  value: z.number(),
  datasetSlug: z.optional(z.string()),
});

export const datasetSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string().optional(),
  unit: unitSchema,
  views: z.array(viewTypeSchema),
  measurements: z.array(measurementSchema),
  slug: z.string(),
});
